#!/usr/bin/env python3
"""Shared curation tables.

Single source of truth for both curate.py (builds data.js) and
committee.py (scores the acts). Edit the picks and notes here.
"""

# tier: 1 = must see, 2 = big call, 3 = worth a punt
# genre: rock | indie | dj | global | trad | other
PICKS = {
# ---------------- THURSDAY ----------------
"Annie Mac":            (1, "dj",     "Arena barely open and she's already the biggest party on site. Perfect opening night."),
"Getdown Edits":        (2, "dj",     "Warm-up before Annie Mac on the same stage. Stay put, don't move."),
"Lúnasa":               (2, "trad",   "World-class trad instrumental. The classy end of Thursday."),
"Ailbhe Reddy":         (2, "indie",  "Sharp Dublin indie songwriting to close out the small stage."),
"David Keenan":         (2, "indie",  "Wild, poetic Dundalk performer. Also plays Saturday if you miss this."),
"Zaska":                (2, "indie",  "Neo-soul and funk guitar. Easy landing after the drive down."),
"Niamh Bury":           (3, "trad",   "Gorgeous, quiet folk voice. Good decompression."),
"Mantle":               (3, "rock",   "Kildare indie rock, Pearl Jam and Wunderhorse in the DNA. Early doors."),
"Justyna":              (3, "dj",     "The Last City going properly late on night one."),
"Madonna Kebab":        (3, "dj",     "Ping Pong Disco being exactly as daft as it sounds."),
"Corcra":               (3, "dj",     "House, prog and disco to open the weekend."),
"Bull Horris":          (3, "rock",   "Loose, rowdy Irish outfit."),
"All Things Eve":       (3, "indie",  "One to say you saw early."),

# ---------------- FRIDAY ----------------
"Pulp":                 (1, "indie",  "First festival headline in 15 years. Jarvis, the hits, a field full of people losing it. The single biggest set of the weekend."),
"Floating Points (Live)":(1,"dj",     "Live, not a DJ set — builds from ambient to full euphoria. The best possible thing to do after Pulp."),
"Friendly Fires":       (1, "indie",  "Indie you can actually rave to. 'Paris' and 'Blue Cassette' in a tent at half eight is the sweet spot."),
"Floorplan":            (1, "dj",     "Robert Hood's gospel-house project. Detroit techno royalty and genuinely joyous."),
"Kerri Chandler":       (1, "dj",     "Deep house godfather closing the Bandstand at 1:30am. If you only do one late set Friday, this."),
"Gurriers":             (1, "rock",   "Dublin post-punk on the main stage right before Pulp. Loud, mean and the best homegrown guitar band going."),
"Dry Cleaning":         (2, "rock",   "Deadpan spoken vocals over brilliant angular guitars. Very much your thing."),
"Cardinals":            (2, "rock",   "Cork guitar band with big widescreen tunes. Rising fast."),
"Job Jobse":            (2, "dj",     "Dutch selector who does the euphoric long-form thing better than almost anyone. Arcadia at midnight."),
"O'Flynn":              (2, "dj",     "Percussive, melodic, tribal house. Road To Nowhere after dark."),
"Brògeal":              (2, "trad",   "Folk-punk singalongs. Think a rowdier, scrappier trad night."),
"PVA":                  (2, "rock",   "Post-punk welded to hard electronics. Genuinely heavy in a live room."),
"Anish Kumar":          (2, "dj",     "UK breaks and bass with a big grin on it."),
"Sunil Sharpe x Kev Freeney Presents Spineless": (2,"dj","Ireland's hardest techno operator. Go if you want it fast and unrelenting."),
"Jamz Supernova":       (2, "dj",     "Broken beat, soul, bass. Superb late selector."),
"New Jackson":          (2, "dj",     "David Kitt's electronic alias. Hypnotic Irish house in the dome."),
"Sam Alfred":           (2, "dj",     "Sets up Kerri Chandler on the Bandstand. Don't wander off."),
"Trinity Orchestra":    (2, "other",  "Orchestra doing a full pop/dance album live. Brilliant, silly, great way to open Friday."),
"Jacob Alon":           (2, "indie",  "Fragile, spellbinding folk. Ten minutes in and the tent goes silent."),
"Lullahush":            (2, "indie",  "Irish electronic-folk producer. Beautiful and strange live show."),
"Black Nylon":          (3, "rock",   "Dark, driving Irish guitar music. Late slot on a small stage."),
"Swimming Paul":        (3, "dj",     "Weird, warm Irish electronics at 2am."),
"Surusinghe":           (3, "dj",     "Fast, bass-heavy, no mercy. Closing Arcadia."),
"Kelly Anne Byrne 'Prince Tribute'": (3,"other","Two hours of Prince. Exactly as good as it sounds."),
"megaTRAD":             (3, "trad",   "Trad turned up to eleven. The Last City gets rowdy."),
"Trad Folkin'Raves feat Annie Craic": (3,"trad","Trad rave until 4am. Chaos in the best way."),
"The New Eves":         (3, "indie",  "Odd, ritualistic, brilliant. Not like anything else on."),
"Hank":                 (3, "rock",   "Scrappy guitar band, early afternoon, low commitment."),
"The Awning":           (3, "indie",  "Solid Irish indie on the Hidden Sounds stage."),
"Rory Sweeney (Live)":  (3, "dj",     "Live electronics in The Circle."),
"Rose Betts":           (3, "indie",  "Big-voiced songwriting."),
"Peach":                (3, "dj",     "Reliably great house selector, early IMMERSE slot."),
"Huartan":              (3, "trad",   "Trad with teeth."),
"MIKE":                 (3, "other",  "Cult New York rapper. Hazy, heavy, worth the detour."),
"Sexy Tadhg":           (3, "other",  "An absolute lunatic on the main stage. Pure Irish festival chaos."),
"Dublin Disco All Dayer DJ's": (3,"dj","Disco all night in Ping Pong."),

# ---------------- SATURDAY ----------------
"Maruja":               (1, "rock",   "The heaviest thing on the entire bill. Sax-driven noise-rock that goes full doom. If you want something genuinely punishing, this is it."),
"Gilla Band":           (1, "rock",   "Ireland's greatest noise band. Physically overwhelming live — a wall of broken electronics and screaming. Unmissable."),
"W.I.T.C.H.":           (1, "global", "Zambian psych-rock legends, back after 40 years. Fuzzed-out guitars and afro-rock grooves. If Arc De Soleil's afternoon set was your favourite thing last year, this is the 2026 version of it — guitar-led psychedelic groove band, mid-size stage, sunshine slot. A total joy."),
"Hot 8 Brass Band":     (1, "global", "New Orleans brass with a sub-bass tuba. Impossible not to move. Perfect early evening main stage."),
"Ezra Collective":      (1, "global", "Mercury-winning London jazz that plays like a carnival. One of the best live bands on earth right now."),
"Sprints":              (1, "rock",   "Dublin punk, absolutely relentless. Karla Chubb is a proper frontperson."),
"THUMPER":              (1, "rock",   "Two drummers, huge noise-pop hooks. The Last City will come apart at the seams."),
"Maribou State (Live)": (1, "dj",     "Full live band version of their soulful electronica. Gorgeous and huge."),
"The Avalanches (DJ Set)": (1,"dj",   "Sample-collage legends going back-to-back on records until 3am. A once-in-a-while thing."),
"Mall Grab":            (1, "dj",     "Raw, rowdy lo-fi house and rave. Closing the Bandstand at 1:30."),
"Joy Orbison":          (1, "dj",     "UK bass and house royalty. Arcadia at 1am is where he belongs."),
"Greentea Peng":        (1, "global", "Psychedelic neo-soul with heavy dub and reggae bones. Smoky and brilliant."),
"Bicurious":            (2, "rock",   "Irish math-rock duo. Absurdly heavy for two people."),
"Call Super":           (2, "dj",     "Left-field, textured, beautiful club music to close Arcadia."),
"DJ Nobu":              (2, "dj",     "Japanese techno master. Deep, dark, disciplined."),
"Dan Shake":            (2, "dj",     "House, disco and boogie. Guaranteed good time."),
"Jyoty":                (2, "dj",     "Everything from garage to bashment. Total party selector."),
"Or:la":                (2, "dj",     "Derry-born, wonky and hard-hitting."),
"Say She She":          (2, "global", "NYC disco-soul trio. Live band, huge harmonies, midnight slot."),
"KhakiKid":             (2, "other",  "Dublin hip hop with a great sense of humour."),
"David Kitt":           (2, "indie",  "Irish indie-electronic elder statesman. Lovely early afternoon set."),
"Muireann Bradley":     (2, "trad",   "Teenage Donegal fingerpicker playing 1920s country blues. Jaw-dropping."),
"Colleen Cosmo Murphy": (2, "dj",     "Three hours of proper disco to open the dome. Best early-day option on site."),
"Moving Still":         (2, "dj",     "Irish-Saudi DJ mixing SWANA sounds with house. Excellent."),
"Cromby":               (2, "dj",     "Belfast house, always delivers."),
"The Wild Geeze - Comedy Cabaret": (2,"other","Three hours of Irish comedy. Best possible hangover cure."),
"Sassy 009":            (3, "indie",  "Norwegian dream-pop-meets-club. Odd and lovely."),
"The Itch":             (3, "rock",   "Young, snotty and loud. Early doors guitar hit."),
"Seamus Fogarty":       (3, "indie",  "Wry Irish folk-electronica."),
"Yankari Afrobeat Collective": (3,"global","Afrobeat until half three in the morning."),
"Franz Scala":          (3, "dj",     "Italo, cosmic disco, weirdness."),
"Gaff E":               (3, "dj",     "Irish DJ closing Ping Pong Disco at 4am."),
"Governess":            (3, "dj",     "Great Irish selector, plays Friday and Saturday."),
"DJ Deece":             (3, "dj",     "Late one in the dome."),
"Æ MAK":                (3, "indie",  "Art-pop with a real edge."),
"Maykay":               (3, "rock",   "Big voice, big songs."),
"Ria Rua":              (3, "rock",   "Electronic-punk crossover. Aggressive and good."),
"One Leg One Eye":      (3, "trad",   "Trad drone. Genuinely unsettling and brilliant."),
"Glasshouse presents: Bjork": (3,"other","Björk covers by a live collective. Bold move, usually works."),
"Nialler9":             (3, "dj",     "The Irish music blogger. Excellent, tasteful selections."),
"Takuya Nakamura (Live)": (3,"dj",    "Live trumpet over dub and house."),
"Bedlam":               (3, "dj",     "Late and loud in The Last City."),
"LOST at The Last City": (3,"dj",     "Legendary Irish rave crew. 1am to 4am."),
"Spray":                (3, "dj",     "Hard, fast IMMERSE slot."),
"EMA":                  (3, "dj",     "Irish techno, late."),
"Sing Along Social":    (3, "other",  "Mass karaoke, no talent required. Genuinely great craic at 3pm."),
"Sun Studio Collective":(3, "rock",   "Rock'n'roll revivalists."),
"Acid Granny Presents Schindler's Fist": (3,"other","Exactly as unhinged as the name suggests."),
"Felispeaks":           (3, "other",  "Powerful Irish-Nigerian performer."),
"Trá Pháidín":          (3, "trad",   "Trad session done properly."),

# ---------------- SUNDAY ----------------
"Underworld":           (1, "dj",     "Third time at ATN and they still turn a field into a rave. 'Born Slippy' outdoors on a Sunday night is the weekend's peak moment."),
"Disclosure (DJ)":      (1, "dj",     "Main stage midnight DJ set to close the whole festival. Hits, house, everyone."),
"Mogwai":               (1, "rock",   "Scottish post-rock at absolutely crushing volume. The closest thing to metal all weekend, and the loudest set on site. Clashes with Underworld's tail — see the plan."),
"Barrington Levy":      (1, "global", "Genuine reggae and dancehall royalty. 'Here I Come' in the afternoon sun. The reggae set of the weekend, no contest."),
"Anna von Hausswolff":  (1, "rock",   "Pipe organ doom. Gothic, monolithic, genuinely heavy. Metal fans get this immediately."),
"King Kong Company":    (1, "dj",     "Waterford's own. Live electronic mayhem on home turf at 1:30am — this will be the most unhinged room at the festival."),
"Hot Chip (DJ Set)":    (1, "dj",     "Hot Chip playing records. Nailed-on party."),
"Altern-8":             (1, "dj",     "Original 1991 rave. Dust masks, hoovers, breakbeats. Pure nostalgia and pure energy."),
"Soichi Terada (Live)": (1, "dj",     "The happiest man in house music playing live. Impossible to watch without grinning."),
"Talks in the Tent: John Cooper Clarke": (1, "other", "The punk poet. Ferociously funny, still razor sharp. Best non-music thing on the bill."),
"Self Esteem":          (2, "indie",  "Huge, theatrical pop with a proper live show."),
"Kate Nash":            (2, "indie",  "'Foundations' and a much heavier live band than you'd expect."),
"Chet Faker":           (2, "indie",  "Smoky electronic soul, ideal Sunday evening."),
"Soda Blonde":          (2, "indie",  "Dublin indie-pop with real craft. Opens the main stage."),
"Damien Dempsey":       (2, "indie",  "An Irish institution. Thousands of people singing every word. A moment."),
"Eats Everything":      (2, "dj",     "Big-room house, closing Arcadia at 4am."),
"The Dare (DJ Set)":    (2, "dj",     "Sleazy electroclash revival. Very fun, very late."),
"Weval (Live)":         (2, "dj",     "Dutch duo, live and melodic. Beautiful visuals."),
"Prosumer":             (2, "dj",     "Warm, soulful house from a true master. Perfect Sunday teatime."),
"Gabrielle Kwarteng":   (2, "dj",     "Rolling, groovy house."),
"Anz b2b Jio":          (2, "dj",     "Rapid, colourful UK club music."),
"Ms Dynamite":          (2, "global", "Garage and dancehall legend. 'Booo!' still hits."),
"Moonchild Sanelly":    (2, "global", "South African gqom-punk. Absolutely wild live."),
"Getdown Services":     (2, "rock",   "Sardonic Bristol post-punk. Very funny, very tight."),
"Kean Kavanagh":        (2, "indie",  "Softboy Records, smooth Irish alt-pop."),
"Alabaster DePlume":    (2, "other",  "Spoken word and saxophone. Odd, gentle, hypnotic."),
"SOAK":                 (2, "indie",  "Derry songwriter, quietly devastating."),
"Playback Presents: Stop Making Sense": (2,"other","Talking Heads' concert film, live band treatment. Guaranteed singalong."),
"Bazza Ranks":          (2, "global", "Reggae and dancehall selector. Two hours of pure sunshine."),
"BIIRD":                (2, "indie",  "Irish supergroup-ish indie. Building real buzz."),
"Freak Slug":           (3, "indie",  "Hazy Manchester bedroom-pop."),
"Monjola":              (3, "other",  "Irish R&B with big hooks."),
"Mango":                (3, "other",  "Dublin hip hop stalwart."),
"Róis":                 (3, "trad",   "Experimental Irish keening. Haunting."),
"Gently Tender":        (3, "indie",  "Ex-Palma Violets, loose and lovely."),
"Sell Everything":      (3, "rock",   "Loud, closing the Flourish stage."),
"Daniel Wang":          (3, "dj",     "Disco obsessive closing Ping Pong at 4am."),
"Stevie G":             (3, "dj",     "Cork legend, hip hop and soul."),
"Marcus O'Laoire":      (3, "dj",     "Great taste, great Sunday evening groove."),
"Grooveline":           (3, "dj",     "Funk and soul on the Bandstand."),
"Burt Bacharach by Paddy Hanna": (3,"other","Bacharach songbook, sincerely done."),
"Toshín":               (3, "global", "Irish-Nigerian soul."),
"Elikya":               (3, "global", "Congolese-Irish, late and joyous."),
"Qbanaa":               (3, "global", "Cuban energy on Global Roots."),
"I Draw Slow":          (3, "trad",   "Irish bluegrass, done well."),
"Winemoms":             (3, "dj",     "1am to 4am, last stand of the weekend."),
"Tony Cantwell":        (3, "other",  "Very funny Irish comedian."),
"Organ Freeman (Live Jazz)": (3,"other","Live jazz to open Sunday gently."),
"Shrem's Madonnathon":  (3, "dj",     "Two hours of Madonna. No notes."),
"The Calvinists":       (3, "rock",   "Rowdy guitars on Global Roots."),
"Sloucho":              (3, "dj",     "Irish producer, late IMMERSE."),
}

# How they've actually been live over the last year or so.
# artist: (comment, review_url, source_name)   — url/source may be "" where no
# recent written review exists; the comment says so plainly in that case.
LIVE = {
"Pulp": ("Reviewers on the 2025 'Here Comes More' run were near-unanimous: they're playing two sets with an interval to fit the hits, the deep cuts and the new album in, and Jarvis is on imperious form. One of the most warmly received comebacks in years.",
  "https://www.uncut.co.uk/reviews/reviewed-pulp-the-o2-london-june-13-2025-150109/", "Uncut, O2 London"),
"Underworld": ("2025 shows were called a masterclass in pacing — no filler, no banter, just Hyde and Smith building a near-spiritual arc. Setlists spanned 'Pearl's Girl' and 'Juanita' through to newer 'Denver Luna'.",
  "https://www.inyourbones.live/show-reviews/underworld", "InYourBones"),
"Mogwai": ("Played Vicar Street in Dublin in July 2025 and Leeds in February — reviewers describe a 90-minute swing between fragile beauty and eardrum-shredding noise blasts. Three guitars, and the new material holds up against the classics.",
  "https://nomoreworkhorse.com/2025/07/28/mogwai-vicar-st-26-07-25-live-review/", "No More Workhorse, Vicar St"),
"Maruja": ("The live reputation is the whole point with this band — 'ritualistic, theatrical', improvisation-led, swinging between introspection and snarling rage. Their Manchester Academy 3 show in September 2025 was reviewed as genuinely transformative.",
  "https://mancunion.com/2025/09/25/live-review-manchester-maruja-academy-3/", "The Mancunion, Academy 3"),
"Gilla Band": ("Two sold-out Dublin nights in October 2025 were called 'unhinged and seriously noisy', peaking early with a delirious, pogoing crowd. They don't tour much — this is the one to prioritise.",
  "https://nomoreworkhorse.com/2025/10/28/gilla-band-the-workmans-club-26-10-25-live-review/", "No More Workhorse, Workmans"),
"Ezra Collective": ("Critics' consensus across 32 reviews rates them an outstanding live act. At the Sydney Opera House in 2025 the entire seated hall got up and danced — that's the standard reaction.",
  "https://www.liverate.com/artists/ezra-collective", "LiveRate consensus"),
"Sprints": ("Closed their 2025 UK/Ireland leg with a sold-out Vicar Street homecoming described as 'a thrilling 1 hour 40 of pure joy'. Karla Chubb is a genuinely commanding frontperson.",
  "https://www.godisinthetvzine.co.uk/2025/11/25/live-sprints-yard-vicar-street-dublin-20-11-2025/", "God Is In The TV, Vicar St"),
"THUMPER": ("Their Academy headliner was called 'a raucous night of joy' and 'a band at the peak of their powers' — still chaotic, but noticeably tighter and more polished than the early days.",
  "https://headstuff.org/entertainment/music/thumper-academy-live-review/", "HeadStuff, The Academy"),
"Gurriers": ("Yes — genuinely good, and a real live band rather than a studio one. Sold out Scala in London in 2025 off the back of 'Come And See', with the singer regularly out in the crowd. Chaotic, fast and aggressive.",
  "https://whenthehornblows.com/content/2025/3/31/live-review-gurriers-scala-london-27032025", "When The Horn Blows, Scala"),
"W.I.T.C.H.": ("At Wide Awake 2025 they were described as injecting life into the crowd with radiant, funk-laced grooves. Frontman Jagari Chanda, now in his 70s, was called a festival-favourite frontman at Woodsist the same year.",
  "https://www.earsmelt.com/post/wide-awake-festival-2025-review", "Ears Melt, Wide Awake"),
"Greentea Peng": ("The 2025 'Tell Dem It's Sunny' tour drew consistently strong reviews — sets flowing through dub, drum'n'bass and jungle, with a magnetic stage presence. Albert Hall Manchester was a highlight.",
  "https://mancunion.com/2025/05/12/greentea-peng-live/", "The Mancunion, Albert Hall"),
"Self Esteem": ("The 'A Complicated Woman' shows are staged like theatre, in acts, with an ensemble cast — sold-out 2000-capacity nights and reviews calling her one of Britain's greatest current live performers.",
  "https://whenthehornblows.com/content/2025/10/11/live-review-self-esteem-brixton-academy-london-09102025", "When The Horn Blows, Brixton"),
"Anna von Hausswolff": ("Reviewers of the 2025 'Iconoclasts' tour describe the sheer physicality as staggering — pipe organ, synths, bass and thunderous drums colliding, with a voice called almost animalistic. Sold out Electric Brixton.",
  "https://karmamagazine.co.uk/2025/12/06/a-catharic-and-transformative-journery-into-the-self-with-anna-von-hausswolff-in-copenhagen/", "Karma, Copenhagen"),
"Floating Points (Live)": ("Four sold-out Outernet shows in London in January 2025 were reviewed as a dazzling audiovisual spectacle — Sam Shepherd hunched over a modular synth, with live reactive visuals. The live show is a different beast to the DJ sets.",
  "https://www.rollingstone.co.uk/music/floating-points-here-outernet-london-live-review-47007/", "Rolling Stone UK, Outernet"),
"Maribou State (Live)": ("The 2025 'Hallucinating Love' tour was their return after six years and Chris Davids' brain surgery — reviews called the Bristol shows deeply moving, and they sold out multiple Alexandra Palace nights within hours.",
  "https://www.thevancouverartsreview.com/2025/04/smooth-layered-original-maribou-state-kick-off-the-hallucinating-love-tour/", "Vancouver Arts Review"),
"Mall Grab": ("Two sold-out Carriageworks shows for Vivid Sydney 2025 — opened at nearly 140bpm and swung into drum'n'bass. Reviewers call his sets fast, physical and unpredictable.",
  "https://beat.com.au/mall-grab-transforms-carriageworks-into-high-octane-rave-paradise-for-vivid-sydney/", "Beat, Vivid Sydney"),
"Moonchild Sanelly": ("Supported Self Esteem across 2025 and repeatedly stole the reviews — 'energy, artistry and humanity' and 'utterly magnificent', with the crowd eating out of her hand. Her 'future ghetto funk' is built for a festival tent.",
  "https://atthebarrier.com/2025/09/28/self-esteem-manchester-academy-live-review/", "At The Barrier, Manchester"),
"Talks in the Tent: John Cooper Clarke": ("Consensus across 21 reviews rates him a superb live performer — 'poetic, joyous, versatile'. Sold out Salford Lads Club in June 2025 and still touring hard at 77.",
  "https://louderthanwar.com/john-cooper-clarke-salford-lads-club-live-review/", "Louder Than War, Salford"),
"Dry Cleaning": ("Consensus across 58 reviews: captivating, riveting, intense. They played their biggest headline show to date at Brixton Academy off the back of 'Secret Love'. Sets run short — 45 to 75 minutes.",
  "https://www.liverate.com/artists/dry-cleaning", "LiveRate consensus"),
"Friendly Fires": ("Critics rate them an impressive live act — 'rhythmic, charismatic, kaleidoscopic'. Recent setlists are hits-dense: 'Paris', 'Kiss of Life', 'Jump in the Pool', 'Blue Cassette'. Ed Macfarlane's dancing is the show.",
  "https://www.liverate.com/artists/friendly-fires", "LiveRate consensus"),
"Rahann": ("Billed here as 'Rahann' — this is Chicago's Rahaan, who came up dancing to Ron Hardy at the Music Box. A Resident Advisor review of his London set praised how carefully he builds and releases a floor: disco, soulful house and edits, no showboating.",
  "https://ra.co/reviews/8548", "Resident Advisor, London"),
"Kerri Chandler": ("Thirty years of shaping house music, and his reel-to-reel sets — mixing off four tape machines — are the stuff of legend. Described as incredibly skilled and rehearsed to the point of precision.",
  "https://djmag.com/news/watch-kerri-chandler-play-reel-reel-live-set-roundhouse-london", "DJ Mag, Roundhouse"),
"Soichi Terada (Live)": ("Widely called the custodian of electronic music's cheeriest live set — soulful, melodic deep house played with visible delight. Impossible to watch grumpily.",
  "https://crackmagazine.net/article/profiles/soichi-terada/", "Crack Magazine"),
"Kate Nash": ("No major broadsheet reviews from the last year, but audience reports from the 2025 run are consistently strong — 'full of energy', good crowd connection, and a set that mixes 'Made of Bricks' hits with the newer, harder material.",
  "", ""),
"Barrington Levy": ("Worth being straight with you: reactions to his 2025 US 'Here I Come' run were mixed — some crowds raved about the energy, one reviewer called it a let-down. The songs are untouchable; the performance can be variable.",
  "", ""),
"Hot 8 Brass Band": ("No written review from the last year turned up, but they played New Orleans Jazz Fest 2025 and released 'Big Tuba' in February. Their set is built on covers — 'Sexual Healing', 'Ain't No Sunshine' — and it works on any crowd.",
  "", ""),
"King Kong Company": ("No press review from the last year surfaced, so this is reputation rather than a citation — but their live show is the entire basis of their following, and they sold out a hometown Waterford show at Bank Lane. On home turf at 1:30am, expect bedlam.",
  "", ""),
"The Avalanches (DJ Set)": ("No 2025 set review turned up in the search, so treat this as reputation: their DJ sets lean on the sample-collage sensibility of the records rather than being a straight club set. Two hours, on the last full night.",
  "", ""),
}

# A signature track per act, used to build the listen links. These become SEARCH
# deep-links (YouTube / Spotify / Apple Music) rather than hardcoded track IDs —
# a guessed video ID is a dead link, a search always resolves. Acts left out here
# still get artist-only search links.
SONGS = {
"Pulp": "Common People", "Underworld": "Born Slippy NUXX", "Mogwai": "Take Me Somewhere Nice",
"Maruja": "Thunder", "Gilla Band": "Why They Hide Their Bodies Under My Garage",
"Ezra Collective": "Victory Dance", "W.I.T.C.H.": "Lazy Bones", "Hot 8 Brass Band": "Sexual Healing",
"Sprints": "Literary Mind", "THUMPER": "Topher Grace", "Gurriers": "Approachable",
"Dry Cleaning": "Scratchcard Lanyard", "Friendly Fires": "Paris",
"Floating Points (Live)": "LesAlpx", "Kerri Chandler": "Rain", "Floorplan": "Never Grow Old",
"Self Esteem": "I Do This All The Time", "Kate Nash": "Foundations",
"Barrington Levy": "Here I Come", "Anna von Hausswolff": "The Truth, The Glow, The Fall",
"Chet Faker": "Talk Is Cheap", "Soda Blonde": "Terrible Hands", "Damien Dempsey": "It's All Good",
"Disclosure (DJ)": "Latch", "Hot Chip (DJ Set)": "Over and Over", "Altern-8": "Activ 8",
"Soichi Terada (Live)": "Sun Shower", "Talks in the Tent: John Cooper Clarke": "Evidently Chickentown",
"Moonchild Sanelly": "Undumping", "Greentea Peng": "Hu Man", "Maribou State (Live)": "Kingdom",
"The Avalanches (DJ Set)": "Frontier Psychiatrist", "Mall Grab": "Sunflower",
"Joy Orbison": "Hyph Mngo", "Say She She": "Forget Me Not", "Ms Dynamite": "Dy-Na-Mi-Tee",
"SOAK": "Sea Creatures", "Getdown Services": "Crisis",
"Alabaster DePlume": "Don't Forget You're Precious", "The Dare (DJ Set)": "Girls",
"Weval (Live)": "Someday", "David Kitt": "Song From Hope Street", "PVA": "Untethered",
"O'Flynn": "Tyrion", "Muireann Bradley": "Candyman", "Trinity Orchestra": "",
}

def listen_links(artist, song):
    """Search deep-links that always resolve, rather than guessed track IDs."""
    from urllib.parse import quote
    q = quote((artist + " " + song).strip())
    return {
        "yt": "https://www.youtube.com/results?search_query=" + q,
        "sp": "https://open.spotify.com/search/" + q,
        "am": "https://music.apple.com/search?term=" + q,
    }

# Acts deliberately left out of the curated picks. They still appear in the full
# schedule browser — this list only controls what gets recommended.
EXCLUDE = {
    "KNEECAP", "Kae Tempest", "For Those I Love", "Jinx Lennon",
    "Joshua Idehen", "Christy Moore", "The Mary Wallopers",
}



STAGE_NAMES = {
    "the-big-romance-dome-x-altos": "Big Romance Dome x Altos",
}
