#!/usr/bin/env python3
"""Turn the raw clashfinder scrape into data.js for the guide app.

Re-run after editing PICKS:  python3 curate.py
"""
import json, re

from curate_tables import (PICKS, LIVE, SONGS, EXCLUDE, STAGE_NAMES,
                            DESC, STAGE_DESC, FEST, listen_links)

DAY_KEY = {
    "Thursday 30th July": "thu",
    "Friday 31st July":   "fri",
    "Saturday 1st August":"sat",
    "Sunday 2nd August":  "sun",
}

raw = json.load(open("_schedule_raw.json"))

try:
    COMMITTEE = json.load(open("committee.json"))
except FileNotFoundError:
    raise SystemExit("run committee.py first: python3 committee.py && python3 curate.py")
CSCORES = COMMITTEE["scores"]

sets = []
for r in raw:
    a = r["artist"]
    tier, genre, note = PICKS.get(a, (0, "", ""))
    if a in EXCLUDE:
        tier, genre, note = 0, "", ""
    lv, lu, ls = LIVE.get(a, ("", "", ""))
    song = SONGS.get(a, "")
    ln = listen_links(a, song)
    cs = CSCORES.get(a) or {}
    stage = STAGE_NAMES.get(r["stage"], r["stage"])
    fv, fn = FEST.get(a, ("", ""))
    sets.append({
        "de": DESC.get(a) or STAGE_DESC.get(stage, ""),
        "fv": fv,                      # festival form verdict
        "fn": fn,                      # festival form note
        "cs": cs.get("c", 0),          # consolidated composite (base + legend bonus)
        "cb": cs.get("b", 0),          # base, the equal three-way split
        "cn": cs.get("bn", 0),         # legend bonus
        "cx": cs.get("f", 0),          # freshness of current material
        "cp": cs.get("p", 0),          # best album
        "cd": cs.get("bs", 0),         # bench strength
        "cr": cs.get("r", 0),          # recent concerts
        "cf": cs.get("cf", 0),         # confidence in the recent figure
        "lw": cs.get("lw", ""),        # the legendary gig
        "ln": cs.get("ln", ""),        # when it was
        "sg": song,
        "yt": ln["yt"], "sp": ln["sp"], "am": ln["am"],
        "a": a,
        "s": stage,
        "d": DAY_KEY[r["day"]],
        "t": r["time"],
        "st": r["start"],
        "en": r["end"],
        "tr": tier,
        "g": genre,
        "n": note,
        "lv": lv,
        "lu": lu,
        "ls": ls,
    })

sets.sort(key=lambda x: x["st"])

for label, table in (("PICKS", PICKS), ("LIVE", LIVE)):
    unmatched = sorted(set(table) - set(s["a"] for s in sets))
    if unmatched:
        print("!! %s entries with no matching set (typo?):" % label)
        for u in unmatched:
            print("   -", u)

out = "// Generated by curate.py — do not hand-edit.\nwindow.ATN_DATA = " + \
      json.dumps(sets, ensure_ascii=False, separators=(",", ":")) + ";\n" + \
      "window.ATN_HOURS = " + \
      json.dumps(COMMITTEE["hours"], ensure_ascii=False, separators=(",", ":")) + ";\n" + \
      "window.ATN_MODEL = " + json.dumps(COMMITTEE["model"]) + ";\n" + \
      "window.ATN_JUDGES = " + json.dumps(COMMITTEE["judges"]) + ";\n" + \
      "window.ATN_BUILD = " + json.dumps(__import__("datetime").datetime.now().strftime("%d %b %Y, %H:%M")) + ";\n"
open("data.js", "w", encoding="utf-8").write(out)

from collections import Counter
print(f"wrote data.js — {len(sets)} sets, {sum(1 for s in sets if s['tr'])} curated picks")
print(Counter(s["g"] for s in sets if s["g"]))
